version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jonisql112233
      MYSQL_DATABASE: gestorusuarios
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - crm_network

  servicio-users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: servicio-users
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gestorusuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Jonisql112233
      JWT_SECRET: eeGEQ3snVxhhzn5N8YJY9BfJh9b1V1pZBfNdNgslYX4=
      JWT_EXPIRATION: 86400000
    networks:
      - crm_network

  servicio-clientes:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: servicio-clientes
    ports:
      - "8085:8085"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gestorusuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Jonisql112233
      JWT_SECRET: eeGEQ3snVxhhzn5N8YJY9BfJh9b1V1pZBfNdNgslYX4=
    networks:
      - crm_network

  servicio-ventas:
    build:
      context: ./ventas
      dockerfile: Dockerfile
    container_name: servicio-ventas
    ports:
      - "8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gestorusuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Jonisql112233
      JWT_SECRET: eeGEQ3snVxhhzn5N8YJY9BfJh9b1V1pZBfNdNgslYX4=
      CATALOG_SERVICE_URL: http://servicio-servicios:8083
    networks:
      - crm_network


  servicio-servicios:
    build:
      context: ./microservicios   # <- usa aquí la carpeta real de tu MS de servicios
      dockerfile: Dockerfile
    container_name: servicio-servicios
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gestorusuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Jonisql112233
      JWT_SECRET: eeGEQ3snVxhhzn5N8YJY9BfJh9b1V1pZBfNdNgslYX4=
    networks:
      - crm_network

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      servicio-users:
        condition: service_started
      servicio-clientes:
        condition: service_started
      servicio-ventas:
        condition: service_started
      servicio-servicios:
        condition: service_started
    environment:
      JWT_SECRET: eeGEQ3snVxhhzn5N8YJY9BfJh9b1V1pZBfNdNgslYX4=
      SPRING_CLOUD_GATEWAY_FORWARDED_HEADERS_ENABLED: "true"
    networks:
      - crm_network

networks:
  crm_network:
    driver: bridge
