server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forwarded:
        headers:
          enabled: true

      routes:
        - id: auth-route
          uri: https://users-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/auth/**
          filters:
            - PreserveHostHeader

        - id: users-route
          uri: https://users-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/users/**
          filters:
            - PreserveHostHeader

        - id: microservicio-clientes
          uri: https://cliente-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/clientes/**
          filters:
            - PreserveHostHeader


        - id: microservicio-leads
          uri: http://servicio-leads:8082
          predicates:
            - Path=/api/leads/**
          filters:
            - PreserveHostHeader

        - id: microservicio-ventas
          uri: http://servicio-ventas:8084
          predicates:
            - Path=/api/oportunidades/**
          filters:
            - PreserveHostHeader

        - id: microservicio-servicios
          uri: http://servicio-microservicios:8085
          predicates:
            - Path=/api/servicios/**
          filters:
            - PreserveHostHeader

jwt:
  secret: eeGEQ3snVxhhzn5N8YJY9BfJh9b1V1pZBfNdNgslYX4=

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.api.gateway.jwt.JwtAuthenticationFilter: DEBUG

