server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forwarded:
        headers:
          enabled: true

      routes:
        - id: auth-route
          uri: https://users-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/auth/**

        - id: users-route
          uri: https://users-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/users/**

        - id: microservicio-clientes
          uri: https://cliente-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/clientes/**

        - id: microservicio-leads
          uri: https://leads-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/leads/**

        - id: microservicio-ventas
          uri: https://ventas-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/oportunidades/**

        - id: microservicio-servicios
          uri: https://microservicios-services-976321280197.us-central1.run.app
          predicates:
            - Path=/api/servicios/**

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.api.gateway.jwt.JwtAuthenticationFilter: DEBUG
