server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Evita headers CORS duplicados
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      # Rutas a microservicios (por nombre de servicio en la red Docker)
      routes:
        - id: auth-route
          uri: http://servicio-users:8081
          predicates:
            - Path=/api/auth/**

        - id: users-route
          uri: http://servicio-users:8081
          predicates:
            - Path=/api/users/**

        - id: microservicio-clientes
          uri: http://servicio-clientes:8085
          predicates:
            - Path=/api/clientes/**

        - id: microservicio-ventas
          uri: http://servicio-ventas:8082
          predicates:
            - Path=/api/sales/**

        - id: microservicio-catalog
          uri: http://servicio-servicios:8083
          predicates:
              - Path=/api/catalog/**
          filters:
            - StripPrefix=0

  # CORS para el front
  web:
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "https://*.vercel.app"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
        - X-Requested-With
      exposed-headers:
        - Location
        - ETag
        - Link
        - X-Total-Count
      allow-credentials: true
      max-age: 3600
